"""add shipment value

Revision ID: 7128700a6766
Revises: 3607574caa47
Create Date: 2026-08-01 00:05:58.524647

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7128700a6766'
down_revision: str | Sequence[str] | None = '3607574caa47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "shipments",
        sa.Column(
            "shipment_value_sar",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'shipment_value_sar')
    # ### end Alembic commands ###
